//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeding
    {
        public int FeedingID { get; set; }
        public int HorseID { get; set; }
        public int DosageFoodID { get; set; }
        public int FoodID { get; set; }
        public string TimeFeeding { get; set; }
    
        public virtual DosageFood DosageFood { get; set; }
        public virtual Food Food { get; set; }
        public virtual Horse Horse { get; set; }
    }
}
