//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horse()
        {
            this.Feeding = new HashSet<Feeding>();
            this.InfoGroup = new HashSet<InfoGroup>();
        }
    
        public int HorseID { get; set; }
        public string HorseName { get; set; }
        public int HorseAge { get; set; }
        public int SuitID { get; set; }
        public int BreedID { get; set; }
    
        public virtual Breed Breed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feeding> Feeding { get; set; }
        public virtual Suit Suit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoGroup> InfoGroup { get; set; }
    }
}
