//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSportsman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoSportsman()
        {
            this.InfoGroup = new HashSet<InfoGroup>();
        }
    
        public int SportsmanID { get; set; }
        public string SportsmanSurname { get; set; }
        public string SportsmanName { get; set; }
        public string SportsmanPatronymic { get; set; }
        public int SportsmanAge { get; set; }
        public string SportsmanEmail { get; set; }
        public string SportsmanPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoGroup> InfoGroup { get; set; }
    }
}
