//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.DbEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorseSchoolPPEntities : DbContext
    {
        public HorseSchoolPPEntities()
            : base("name=HorseSchoolPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breed> Breed { get; set; }
        public virtual DbSet<DivisionOfTheGroup> DivisionOfTheGroup { get; set; }
        public virtual DbSet<DosageFood> DosageFood { get; set; }
        public virtual DbSet<Feeding> Feeding { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Horse> Horse { get; set; }
        public virtual DbSet<InfoCoach> InfoCoach { get; set; }
        public virtual DbSet<InfoGroup> InfoGroup { get; set; }
        public virtual DbSet<InfoSportsman> InfoSportsman { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Space> Space { get; set; }
        public virtual DbSet<Suit> Suit { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
