//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingID { get; set; }
        public int GroupID { get; set; }
        public int SpaceID { get; set; }
        public string TimeTraining { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Space Space { get; set; }
    }
}
